project:
  type: default

format:
  arxiv-pdf:
    pdf-engine: xelatex
    keep-tex: true
    fontsize: 11pt
    include-in-header:
      - preamble.tex
    colorlinks: true
    linkcolor: blue
    citecolor: blue
    urlcolor: blue
    fig-pos: "H"
